# Generated by Django 5.2 on 2025-04-22 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=200)),
                ('item_id', models.CharField(max_length=200)),
                ('institution_id', models.CharField(blank=True, max_length=200, null=True)),
                ('institution_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'item_id')},
            },
        ),
        migrations.CreateModel(
            name='DailyTransactionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_count', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='home_dailyt_user_id_fa753d_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PlaidAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(max_length=50)),
                ('account_subtype', models.CharField(blank=True, max_length=50, null=True)),
                ('mask', models.CharField(blank=True, max_length=10, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('has_transactions', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('plaid_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='home.plaiditem')),
            ],
            options={
                'indexes': [models.Index(fields=['plaid_item', 'account_id'], name='home_plaida_plaid_i_c4418c_idx')],
                'unique_together': {('plaid_item', 'account_id')},
            },
        ),
        migrations.CreateModel(
            name='PlaidTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=200)),
                ('transaction_id', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField()),
                ('merchant_name', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('pending', models.BooleanField(default=False)),
                ('plaid_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='home.plaiditem')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['plaid_item', 'account_id'], name='home_plaidt_plaid_i_15cee7_idx'), models.Index(fields=['date'], name='home_plaidt_date_0462f9_idx')],
                'unique_together': {('plaid_item', 'transaction_id')},
            },
        ),
    ]
