# Generated by Django 5.2 on 2025-04-27 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_budgetsummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BudgetSummary',
        ),
    ]
