# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    self.driver.get("http://ec2-18-220-40-225.us-east-2.compute.amazonaws.com:8000/")
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("over")
    self.driver.find_element(By.ID, "password").send_keys("over1234")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()

    # Wait until the URL contains '/account/'
    WebDriverWait(self.driver, 10).until(
      lambda driver: "/account/" in driver.current_url
    )

    # Assert the URL is correct
    assert "/account/" in self.driver.current_url, "Login failed or did not redirect to account page"

