# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDeleteAccountTest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_deleteAccountTest(self):
    # Test name: Delete Account Test
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://ec2-18-220-40-225.us-east-2.compute.amazonaws.com:8000/")
    # 2 | setWindowSize | 1380x870 | 
    self.driver.set_window_size(1380, 870)
    # 3 | click | id=username | 
    time.sleep(2)
    self.driver.find_element(By.ID, "username").click()
    # 4 | click | linkText=Register here | 
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "Register here").click()
    # 5 | click | id=username | 
    time.sleep(2)
    self.driver.find_element(By.ID, "username").click()
    # 6 | type | id=username | Nick
    self.driver.find_element(By.ID, "username").send_keys("Nick")
    # 7 | click | css=.row | 
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".row").click()
    # 8 | click | id=email | 
    time.sleep(2)
    self.driver.find_element(By.ID, "email").click()
    # 9 | type | id=email | geraldpruitt64@gmail.com
    self.driver.find_element(By.ID, "email").send_keys("geraldpruitt64@gmail.com")
    # 10 | click | id=password1 | 
    time.sleep(2)
    self.driver.find_element(By.ID, "password1").click()
    # 11 | type | id=password1 | ABC123
    self.driver.find_element(By.ID, "password1").send_keys("ABC123")
    # 12 | click | css=.mb-3:nth-child(5) | 
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".mb-3:nth-child(5)").click()
    # 13 | click | css=.mb-3:nth-child(5) > .form-text | 
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".mb-3:nth-child(5) > .form-text").click()
    # 14 | click | id=password2 | 
    time.sleep(2)
    self.driver.find_element(By.ID, "password2").click()
    # 15 | type | id=password2 | ABC123
    self.driver.find_element(By.ID, "password2").send_keys("ABC123")
    # 16 | click | css=.btn | 
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    # 18 | click | css=.btn-danger | 
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-danger").click()
    # 19 | webdriverChooseOkOnVisibleConfirmation |  | 
    self.driver.switch_to.alert.accept()
    # 20 | close |  | 
    self.driver.close()
  
